  name: CI
  on:
    push:
      branches: [ "main" ]
    schedule:
      - cron: '19 19 19 * *'
    workflow_dispatch:

  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.1

    build:
      runs-on: ubuntu-latest
      needs: lint
      strategy:
        matrix:
          folder: [snapcast-client, snapcast-server, beets, mpd, alsa-web]
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Set image tag and metadata
          run: |
            echo "IMAGE_TAG=$(date +%Y%m%d)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            echo "BUILD_DATE=$(date --iso-8601=seconds)" >> $GITHUB_ENV
            echo "VCS_REF=$(git rev-parse HEAD)" >> $GITHUB_ENV

        - name: Log in to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push image
          uses: docker/build-push-action@v6
          with:
            platforms: linux/amd64,linux/arm64
            context: ${{ matrix.folder }}
            pull: true
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.folder }}:latest
            cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.folder }}:buildcache
            cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.folder }}:buildcache,mode=max
            outputs: type=image,name=${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.folder }}:latest,name-canonical=true
